TYPE=VIEW
query=select `warehouse`.`org`.`Org_ID` AS `Org_ID`,`warehouse`.`org`.`OrgName` AS `OrgName`,`warehouse`.`org`.`Address` AS `Address`,`warehouse`.`org`.`Phone` AS `Phone` from `warehouse`.`org`
md5=87a493811f86be10f80f86b8435d149a
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
revision=1
timestamp=2012-04-03 09:18:19
create-version=1
source=select * from org
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `warehouse`.`org`.`Org_ID` AS `Org_ID`,`warehouse`.`org`.`OrgName` AS `OrgName`,`warehouse`.`org`.`Address` AS `Address`,`warehouse`.`org`.`Phone` AS `Phone` from `warehouse`.`org`
